config/routes.rb
Encen::Application.routes.draw do
    
  namespace :admin do
    resources :albums do
      resources :tracks
    end
    resources :concerts, :only => [:index, :edit, :update, :destroy, :new, :create]
    resources :images, :only => :destroy
    resources :pages, :only => [:new, :create, :index, :destroy] do
      resources :images, :only => :create
      resources :page_contents, :only => [:edit, :update, :destroy, :new, :create]
    end
    resources :posts do
      resources :images, :only => :create
    end
    resources :subscriptors, :only => [:index, :destroy]
    resources :users
    root :to => "posts#index"
  end

  devise_for :users, :controllers => {:sessions => 'user_sessions'}
  get "unsubscribe", :to => "mailchimp#unsubscribe"
  match 'contact', :to => "static#contact"
  match 'gallery', :to => "static#gallery"
  match 'newsletter', :to => "static#newsletter"
  resources :albums, :only => [:index, :show] do
    resources :tracks, :only => [:show]
  end
  resources :concerts, :only => :index
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :subscriptors, :only => :create
  root :to => "posts#index"
  match "/:page", :to => "pages#show"
end

app/views/admin/pages/index.html.haml
%h1 Pàgines de text


%p
  = link_to "Crear", new_admin_page_path
  una nova pàgina

%table
  %tr
    %th Identificador
    %th Continguts

  - @pages.each do |page|
    %tr
      %td
        = page.key
        |
        = link_to "Eliminar", [:admin, page], :method => :delete, :confirm => "Estàs segur que vols eliminar aquesta pàgina i tots els seus continguts?"
      %td
        - page.page_contents.each do |content|
          %ul
            -#%li
              -#Idioma: #{ content.locale }
            %li
              Url: #{content.url}
            %li
              = link_to "Editar", edit_admin_page_page_content_path(page, content)
            %li
              = link_to "Eliminar", [:admin, page, content], :method => :delete, :confirm => "Estàs segur que vols eliminar aquest contingut?"

      %td
        %p
          -# unless page.has_all_locales?
          - unless page.page_contents.count == 1
            = link_to "Crear", new_admin_page_page_content_path(page)
            nou contingut per aquesta pàgina.

app/views/admin/pages/new.html.haml
%h1 Nova pàgina de continguts

= simple_form_for [:admin, @page] do |f|
  = f.input :key

  = f.button :submit