config/routes.rb
Encen::Application.routes.draw do
    
  namespace :admin do
    resources :albums do
      resources :tracks
    end
    resources :concerts, :only => [:index, :edit, :update, :destroy, :new, :create]
    resources :images, :only => :destroy
    resources :pages, :only => [:new, :create, :index, :destroy] do
      resources :images, :only => :create
      resources :page_contents, :only => [:edit, :update, :destroy, :new, :create]
    end
    resources :posts do
      resources :images, :only => :create
    end
    resources :subscriptors, :only => [:index, :destroy]
    resources :users
    root :to => "posts#index"
  end

  devise_for :users, :controllers => {:sessions => 'user_sessions'}
  get "unsubscribe", :to => "mailchimp#unsubscribe"
  match 'contact', :to => "static#contact"
  match 'gallery', :to => "static#gallery"
  match 'newsletter', :to => "static#newsletter"
  resources :albums, :only => [:index, :show] do
    resources :tracks, :only => [:show]
  end
  resources :concerts, :only => :index
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :subscriptors, :only => :create
  root :to => "posts#index"
  match "/:page", :to => "pages#show"
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  validates_presence_of :date
  validates_presence_of :city
  validates_presence_of :place
  
  default_scope order('date asc')
  scope :pending, where("date >= ?", Time.now()-2.day).order('date asc')
end

app/controllers/admin/concerts_controller.rb
class Admin::ConcertsController < Admin::AdminController
  # GET /concerts
  # GET /concerts.xml
  def index
    @concerts = Concert.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @concerts }
    end
  end

  # GET /concerts/new
  # GET /concerts/new.xml
  def new
    @concert = Concert.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @concert }
    end
  end

  # GET /concerts/1/edit
  def edit
    @concert = Concert.find(params[:id])
  end

  # POST /concerts
  # POST /concerts.xml
  def create
    @concert = Concert.new(params[:concert])

    respond_to do |format|
      if @concert.save
        format.html { redirect_to admin_concerts_url }
        format.xml  { render :xml => @concert, :status => :created, :location => @concert }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @concert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /concerts/1
  # PUT /concerts/1.xml
  def update
    @concert = Concert.find(params[:id])

    respond_to do |format|
      if @concert.update_attributes(params[:concert])
        format.html { redirect_to admin_concerts_url }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @concert.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1
  # DELETE /concerts/1.xml
  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to(admin_concerts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  # GET /concerts
  # GET /concerts.xml
  def index
    @concerts = Concert.pending

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @concerts }
    end
  end
end

app/views/admin/concerts/_form.html.haml
= simple_form_for [:admin, @concert] do |f|
  -if @concert.errors.any?
    #error_explanation
      %h2= "No s'ha pogut guardar l'entrada degut a #{pluralize(@concert.errors.count, "error")}:"
      %ul
        - @concert.errors.full_messages.each do |msg|
          %li= msg
  = f.input :date, :label => "Data"
  = f.input :event, :label => "Acte"
  = f.input :city, :label => "Municipi"
  = f.input :place, :label => "Lloc"
  = f.button :submit, @concert.new_record? ? "Crear" : "Actualitzar"

app/views/admin/concerts/edit.html.haml
%h1 Editant concert

= render 'form'

.actions
  = link_to 'Enrere', admin_concerts_path

app/views/admin/concerts/index.html.haml
%h1 Concerts

%table
  %tr
    %th Data 
    %th Població
    %th Lloc
    %th Hora
    %th Informació
    %th
    %th

  - @concerts.each do |concert|
    %tr
      %td= concert.date.strftime('%d/%m/%Y')
      %td= concert.city
      %td= concert.place
      %td= concert.date.strftime('%k:%M')
      %td= concert.event
      %td= link_to "Editar", edit_admin_concert_path(concert)
      %td= link_to "Eliminar", [:admin, concert], :method => :delete, :confirm => "N'estàs segur?"

%br

= link_to 'Nou concert', new_admin_concert_path

app/views/admin/concerts/new.html.haml
%h1 Nou concert

= render 'form'

.actions
  = link_to 'Enrere', admin_concerts_path