config/routes.rb
Encen::Application.routes.draw do
    
  namespace :admin do
    resources :albums do
      resources :tracks
    end
    resources :concerts, :only => [:index, :edit, :update, :destroy, :new, :create]
    resources :images, :only => :destroy
    resources :pages, :only => [:new, :create, :index, :destroy] do
      resources :images, :only => :create
      resources :page_contents, :only => [:edit, :update, :destroy, :new, :create]
    end
    resources :posts do
      resources :images, :only => :create
    end
    resources :subscriptors, :only => [:index, :destroy]
    resources :users
    root :to => "posts#index"
  end

  devise_for :users, :controllers => {:sessions => 'user_sessions'}
  get "unsubscribe", :to => "mailchimp#unsubscribe"
  match 'contact', :to => "static#contact"
  match 'gallery', :to => "static#gallery"
  match 'newsletter', :to => "static#newsletter"
  resources :albums, :only => [:index, :show] do
    resources :tracks, :only => [:show]
  end
  resources :concerts, :only => :index
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :subscriptors, :only => :create
  root :to => "posts#index"
  match "/:page", :to => "pages#show"
end

app/views/admin/_menu.html.haml
#admin_menu
  %ul
    %li
      = link_to "Site", root_path
      |
      = link_to "Users", admin_root_path
      |
      = link_to "Translations", interpret_root_path
      |
      = link_to "Posts", admin_posts_path
      |
      = link_to "Newsletter subscriptors", admin_subscriptors_path

#user_menu
  %ul
    %li= current_user.to_s.humanize
    |
    %li
      = link_to "Logout", destroy_user_session_path