config/routes.rb
Encen::Application.routes.draw do
    
  namespace :admin do
    resources :albums do
      resources :tracks
    end
    resources :concerts, :only => [:index, :edit, :update, :destroy, :new, :create]
    resources :images, :only => :destroy
    resources :pages, :only => [:new, :create, :index, :destroy] do
      resources :images, :only => :create
      resources :page_contents, :only => [:edit, :update, :destroy, :new, :create]
    end
    resources :posts do
      resources :images, :only => :create
    end
    resources :subscriptors, :only => [:index, :destroy]
    resources :users
    root :to => "posts#index"
  end

  devise_for :users, :controllers => {:sessions => 'user_sessions'}
  get "unsubscribe", :to => "mailchimp#unsubscribe"
  match 'contact', :to => "static#contact"
  match 'gallery', :to => "static#gallery"
  match 'newsletter', :to => "static#newsletter"
  resources :albums, :only => [:index, :show] do
    resources :tracks, :only => [:show]
  end
  resources :concerts, :only => :index
  resources :posts do
    resources :comments, :only => [:create, :destroy]
  end
  resources :subscriptors, :only => :create
  root :to => "posts#index"
  match "/:page", :to => "pages#show"
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_one :document, :as => :owner, :dependent => :destroy
  mount_uploader :doc, DocumentUploader
  
  default_scope order('created_at asc')
  validates_presence_of :name  
end

app/controllers/admin/tracks_controller.rb
class Admin::TracksController < Admin::AdminController

  # GET /tracks
  # GET /tracks.xml
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.xml
  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.xml
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
    @album = Album.find(params[:album_id])
    
  end

  # POST /tracks
  # POST /tracks.xml
  def create
    @track = Track.new(params[:track])
    @album = Album.find(params[:album_id])
    
    @track.album = @album
        
    respond_to do |format|
      if @track.save
        format.html { redirect_to([:admin, @album], :notice => "Cançó creada correctament") }
        format.xml  { render :xml => @track, :status => :created, :location => @track }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.xml
  def update
    @track = Track.find(params[:id])
    @album = Album.find(params[:album_id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to([:admin, @album], :notice => "Cançó acutalitzada correctament") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.xml
  def destroy
    @track = Track.find(params[:id])
    @album = Album.find(params[:album_id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to(admin_album_url(@album)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/admin/tracks/_form.html.haml
%p#notice= notice
= simple_form_for  [:admin, @album, @track], :html => {:multipart => true} do |f|

	= f.input :name, :label => "Nom pista:"
	= f.label "Lletra:"
	= f.file_field :doc
	= f.hidden_field :doc_cache
	= f.button :submit, @track.new_record? ? "Crear" : "Actualitzar"

app/views/admin/tracks/_track.html.haml
-#%p#notice= notice

%li
  %b= track.name
  - if !track.doc_url.to_s.blank?
    = link_to "Lletra", track.doc_url.to_s, :target => "_blank"
    \|
  = link_to 'Editar', edit_admin_album_track_path(@album,track)
  \|
  = link_to 'Eliminar', admin_album_track_path(@album,track), :method => :delete, :class => "delete", :confirm => "N'estas segur?"

app/views/admin/tracks/edit.html.haml
%h1 Editant pista

= render 'form'

.actions
  = link_to 'Mostrar', [:admin, @album]
  \|
  = link_to 'Enrere', admin_album_path(@album)

app/views/admin/tracks/new.html.haml
%h1 Nova pista

= render 'form'

.actions
  = link_to 'Enrere', admin_albums_path